[versions]
# Android Configuration
compileSdk = "34"
minSdk = "24"
targetSdk = "34"
versionCode = "1100"
versionName = "1.10.000"
ndkVersion = "21.3.6528147"

# App Configuration - SoftCode
softcode-topinfrared = "TC001_DisplaySW_Topinfrared_Adr"
softcode-topinfrared10 = "TC001_DisplaySW_TopinfraredAndroid10_Adr"
softcode-topinfrared-cn = "TC001_DisplaySW_Topinfrared_GB_Adr"
softcode-topinfrared-cn10 = "TC001_DisplaySW_TopinfraredAndroid10_GB_Adr"

# App Configuration - AppKey
appkey-topinfrared = "5B2F6F1FD80844FCB6E50BCA19222E76"
appkey-topinfrared10 = "AD782A05757B458391BFD695A3967EDD"
appkey-topinfrared-cn = "19F791D993B042E2B22D42A974DE92E8"
appkey-topinfrared-cn10 = "058F710E6D3545168F3D19010320F8C3"

# App Configuration - AppSecret
appsecret-topinfrared = "A4A2EE33347A4D7885C26689515567EC"
appsecret-topinfrared10 = "2870276D969B45C1B4A312B336274079"
appsecret-topinfrared-cn = "9D33C48FD7CE4440B7D922FBF9B6DE2A"
appsecret-topinfrared-cn10 = "F4511AAA6C694E54A3676CF2345A4A8E"

# Kotlin and Core
kotlin = "1.8.22"
agp = "8.3.2"
androidx-core = "1.9.0"
androidx-appcompat = "1.6.1"
fragment-ktx = "1.5.5"
material = "1.8.0"
multidex = "2.0.1"

# Lifecycle
lifecycle = "2.6.2"

# Room
room = "2.5.0"

# Work Manager
work = "2.8.1"

# Coroutines
coroutines = "1.6.4"

# Networking
fastjson = "1.2.78"
jsbridge = "1.0.4"
retrofit = "2.9.0"
okhttp = "4.10.0"

# RxJava
rxjava = "2.2.21"
rxandroid = "2.1.1"

# Navigation
arouter = "1.5.2"

# RxLifecycle
rxpermissions = "0.10.2"
rxlifecycle2 = "2.2.2"
rxlifecycle3 = "3.1.0"

# UI Libraries
ucrop = "2.2.4"
play-app-update = "2.1.0"
immersionbar = "3.0.0"
xpopup = "2.9.0"
smart-refresh-layout = "1.1.3"
smart-refresh-layout-v2 = "2.0.3"
smart-refresh-header-v2 = "2.0.5"
brvah = "3.0.7"
colorpickerview = "2.2.4"
photoview = "2.3.0"
nifty = "2.4.0"

# Image Loading
glide = "4.14.2"

# Utils
utilcode = "1.31.1"
xxpermissions = "16.8"
xlog = "1.10.1"
lottie = "5.2.0"
eventbus = "3.3.1"

# Compass and sensor libraries
andromeda = "15.3.0"
andromeda-user = "6.2.0"

# JavaCV
javacv = "1.5.7"

# LMS SDK
lms-international = "3.90.009.0"
lms-china = "3.90.076"

# FFmpeg
ffmpeg = "5.0-1.5.7"

# Third-party services
wechat-sdk = "6.8.0"
umeng-apm = "1.9.0"
zoho-salesiq = "7.0.0"

# Firebase
firebase-bom = "28.4.1"
firebase-messaging = "21.0.1"

# UMeng
umeng-common = "9.6.7"
umeng-asms = "1.8.0"

# Testing
junit = "4.13.2"
test-ext-junit = "1.1.5"
test-espresso-core = "3.5.1"

# Google Services
google-services = "4.3.10"
firebase-crashlytics-gradle = "2.7.1"
huawei-agcp = "1.6.0.300"

# Build Tools
android-gradle-plugin = "8.3.2"
kotlin-gradle-plugin = "1.8.22"

[libraries]
# AndroidX Core
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment-ktx" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
multidex = { group = "androidx.multidex", name = "multidex", version.ref = "multidex" }

# Lifecycle
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }

# Room
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }

# Work Manager
work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work" }

# Kotlin
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }

# Networking
fastjson = { group = "com.alibaba", name = "fastjson", version.ref = "fastjson" }
jsbridge = { group = "com.github.lzyzsd", name = "jsbridge", version.ref = "jsbridge" }
retrofit2 = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
adapter-rxjava2 = { group = "com.squareup.retrofit2", name = "adapter-rxjava2", version.ref = "retrofit" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }

# RxJava
rxjava2 = { group = "io.reactivex.rxjava2", name = "rxjava", version.ref = "rxjava" }
rxandroid = { group = "io.reactivex.rxjava2", name = "rxandroid", version.ref = "rxandroid" }

# Navigation
arouter-api = { group = "com.alibaba", name = "arouter-api", version.ref = "arouter" }
arouter-compiler = { group = "com.alibaba", name = "arouter-compiler", version.ref = "arouter" }

# RxLifecycle
rxpermissions = { group = "com.github.tbruyelle", name = "rxpermissions", version.ref = "rxpermissions" }
rxlifecycle = { group = "com.trello.rxlifecycle2", name = "rxlifecycle", version.ref = "rxlifecycle2" }
rxlifecycle-android = { group = "com.trello.rxlifecycle2", name = "rxlifecycle-android", version.ref = "rxlifecycle2" }
rxlifecycle-components = { group = "com.trello.rxlifecycle2", name = "rxlifecycle-components", version.ref = "rxlifecycle2" }
rxlifecycle-ktx = { group = "com.trello.rxlifecycle3", name = "rxlifecycle-kotlin", version.ref = "rxlifecycle3" }
rxlifecycle-android-lifecycle-ktx = { group = "com.trello.rxlifecycle3", name = "rxlifecycle-android-lifecycle-kotlin", version.ref = "rxlifecycle3" }

# UI Libraries
ucrop = { group = "com.github.yalantis", name = "ucrop", version.ref = "ucrop" }
play-app-update = { group = "com.google.android.play", name = "app-update", version.ref = "play-app-update" }
immersionbar = { group = "com.gyf.immersionbar", name = "immersionbar", version.ref = "immersionbar" }
xpopup = { group = "com.github.li-xiaojun", name = "XPopup", version.ref = "xpopup" }
smart-refresh-layout = { group = "com.scwang.smartrefresh", name = "SmartRefreshLayout", version.ref = "smart-refresh-layout" }
smart-refresh-header = { group = "com.scwang.smartrefresh", name = "SmartRefreshHeader", version.ref = "smart-refresh-layout" }
refresh-layout-kernel = { group = "com.scwang.smart", name = "refresh-layout-kernel", version.ref = "smart-refresh-layout-v2" }
refresh-header-classics = { group = "com.scwang.smart", name = "refresh-header-classics", version.ref = "smart-refresh-header-v2" }
refresh-header-material = { group = "com.scwang.smart", name = "refresh-header-material", version.ref = "smart-refresh-header-v2" }
brvah = { group = "com.github.CymChad", name = "BaseRecyclerViewAdapterHelper", version.ref = "brvah" }
colorpickerview = { group = "com.github.skydoves", name = "colorpickerview", version.ref = "colorpickerview" }
photoview = { group = "com.github.chrisbanes", name = "PhotoView", version.ref = "photoview" }
nifty = { group = "com.nineoldandroids", name = "library", version.ref = "nifty" }

# Image Loading
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
glide-compiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "glide" }

# Utils
utilcode = { group = "com.blankj", name = "utilcodex", version.ref = "utilcode" }
xxpermissions = { group = "com.github.getActivity", name = "XXPermissions", version.ref = "xxpermissions" }
xlog = { group = "com.elvishew", name = "xlog", version.ref = "xlog" }
lottie = { group = "com.airbnb.android", name = "lottie", version.ref = "lottie" }
eventbus = { group = "org.greenrobot", name = "eventbus", version.ref = "eventbus" }

# Compass and sensor libraries
andromeda-core = { group = "com.kylecorry.andromeda", name = "core", version.ref = "andromeda" }
andromeda-sense = { group = "com.kylecorry.andromeda", name = "sense", version.ref = "andromeda" }
compass-sense-user = { group = "com.github.kylecorry31.andromeda", name = "sense", version.ref = "andromeda-user" }
compass-core-user = { group = "com.github.kylecorry31.andromeda", name = "core", version.ref = "andromeda-user" }

# JavaCV
javacv = { group = "org.bytedeco", name = "javacv", version.ref = "javacv" }
javacpp = { group = "org.bytedeco", name = "javacpp", version.ref = "javacv" }

# IR-specific libraries
ir-layout = { group = "com.github.CoderCaiSL", name = "jitpackMvn", version = "+" }

# LMS SDK
lms2-user = { group = "com.topdon.lms.sdk3", name = "lms_international", version.ref = "lms-international" }
lms3-user = { group = "com.topdon.lms.sdk3", name = "lms_china", version.ref = "lms-china" }

# FFmpeg native libraries for IR processing
ffmpeg-android-arm64 = { group = "org.bytedeco", name = "ffmpeg", version.ref = "ffmpeg" }
ffmpeg-android-arm = { group = "org.bytedeco", name = "ffmpeg", version.ref = "ffmpeg" }
ffmpeg-android-x86-64 = { group = "org.bytedeco", name = "ffmpeg", version.ref = "ffmpeg" }
ffmpeg-android-x86 = { group = "org.bytedeco", name = "ffmpeg", version.ref = "ffmpeg" }

# Third-party services
wechat-sdk = { group = "com.tencent.mm.opensdk", name = "wechat-sdk-android", version.ref = "wechat-sdk" }
umeng-apm = { group = "com.umeng.umsdk", name = "apm", version.ref = "umeng-apm" }
zoho-salesiq = { group = "com.zoho.salesiq", name = "mobilisten", version.ref = "zoho-salesiq" }

# Firebase
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging", version.ref = "firebase-messaging" }
firebase-iid = { group = "com.google.firebase", name = "firebase-iid" }

# UMeng
umeng-common = { group = "com.umeng.umsdk", name = "common", version.ref = "umeng-common" }
umeng-asms = { group = "com.umeng.umsdk", name = "asms", version.ref = "umeng-asms" }

# Testing
junit = { group = "junit", name = "junit", version.ref = "junit" }
test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "test-ext-junit" }
test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "test-espresso-core" }

# Build Tools (for buildscript classpath)
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "android-gradle-plugin" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin-gradle-plugin" }
google-services = { group = "com.google.gms", name = "google-services", version.ref = "google-services" }
firebase-crashlytics-gradle = { group = "com.google.firebase", name = "firebase-crashlytics-gradle", version.ref = "firebase-crashlytics-gradle" }
huawei-agconnect = { group = "com.huawei.agconnect", name = "agcp", version.ref = "huawei-agcp" }

[bundles]
androidx-lifecycle = ["lifecycle-runtime-ktx", "lifecycle-viewmodel-ktx", "lifecycle-livedata-ktx"]
rx-lifecycle = ["rxlifecycle", "rxlifecycle-android", "rxlifecycle-components"]
rx-lifecycle-ktx = ["rxlifecycle-ktx", "rxlifecycle-android-lifecycle-ktx"]
retrofit = ["retrofit2", "converter-gson", "adapter-rxjava2", "logging-interceptor"]
smart-refresh = ["smart-refresh-layout", "smart-refresh-header"]
smart-refresh-v2 = ["refresh-layout-kernel", "refresh-header-classics", "refresh-header-material"]
firebase-core = ["firebase-crashlytics", "firebase-analytics", "firebase-messaging", "firebase-iid"]
umeng = ["umeng-common", "umeng-asms"]
andromeda = ["andromeda-core", "andromeda-sense"]
javacv-core = ["javacv", "javacpp"]
ffmpeg-android = ["ffmpeg-android-arm64", "ffmpeg-android-arm", "ffmpeg-android-x86-64", "ffmpeg-android-x86"]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics-gradle" }
huawei-agconnect = { id = "com.huawei.agconnect", version.ref = "huawei-agcp" }